Feat: Login 기능 구현
One-Hundred-Trials/Good-Harvest-Market pull request #83
Opened 2022-12-19 11:37 UTC by khv2644511

### 무엇을 위한 PR인가요?
- [x] 기능 추가 :  Login 기능 구현

### 전달사항
- LoginEmail 페이지에서 회원가입된 정보로 로그인 시, 토큰정보를 불러와 로컬 스토리지에 저장하는 기능을 구현했습니다.

### 변경사항 및 이유
- 이유 : Button 컴포넌트에 navigate를 통한 router이동 기능을 추가했습니다.

### 작업 내역
- 작업 내역 : file changed 참고 부탁드립니다.

### 기대 결과 or 스크린샷

### Issue Number
close : #82

2022-12-19 12:44 UTC, mixnuts211 requested changes
코드 잘봤습니다! 👍

2022-12-19 12:51 UTC, mixnuts211 requested changes
코드 잘봤습니다! 👍

2022-12-19 12:51 UTC, mixnuts211 commented on src/pages/Root.jsx
> +        <React.Fragment>
전체를 감싸고 있는 React.Fragment => PageWrapStyle로 수정 요청드립니다! 페이지 전체를 감싸는 스타일이 적용된 컨테이너입니다 🤗

2022-12-19 13:41 UTC, khv2644511 commented on src/pages/Root.jsx
> +        <React.Fragment>
리뷰 감사합니다~~ :)

2022-12-19 13:42 UTC, merged

2022-12-20 01:50 UTC, KANGPUNGYUN commented on src/pages/Login/LoginEmail/LoginEmail.jsx
> +  const handelSubmit = (e) => {
handleSubmit으로 수정하셔야 될 것 같습니다!